version: '3.7'

services:
  db:
    build: ./db
    restart: always
    container_name: "db"
    volumes:
      - ../db/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  php:
    build: ./php-fpm
    container_name: "php"
    volumes:
      - ../back:/back
  nginx:
    build: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ../back:/back
      - ../nginx/log:/var/log/nginx
    links:
      - php
      - front
  front:
    build: ./front
    container_name: "nuxt"
    ports:
      - "3000:3000"
    volumes:
      -  ../front/:/app/
    depends_on:
      - db
      - php

